### ISSUE TITLE
3.5.1.rc2 Board orientation bug

### ISSUE THREAD

**Issue by oyvinla** [ButterFlight/butterflight#132] opened 2018-04-20 05:42 UTC
it looks like there is something funky going on with the board orientation offset.

two quads with matek F405 and xracer f4 I previously had it at yaw offset 90 deg, now I need to set it to 270deg

one quad with a omnibus f4 positioned backwards. If I set the yaw offset to 180, it is just the same as 0 deg offset. In order to get it correct, I had to adjust yaw 180, pitch 180, roll 180. That does not make sense, since the fc in real life would be back to start (0, 0, 0 deg)

**Comment by nasone32** [comment] 2018-04-20 12:09
issue confirmed on an omnibus f4, had to set yaw to 90

**Comment by kidBrazil** [comment] 2018-04-21 19:03
Closing since andrian's fix has been merged in

**Closed by kidBrazil** 2018-04-21 19:03 UTC
